version: "3"
services:
        nginx:
                image: nginx:stable-alpine
                volumes:
                  - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
                ports:
                  - "20000:80"


        voting:
                build: .
                image: voting:test
                environment:
                  DB_HOST: mysql
                  DB_DATABASE: forge
                  DB_PASSWORD: abobus
                  DB_USERNAME: root
                  REDIS_URL: redis
                ports:
                  - "9000:9000"



        mysql:
                image: mysql
                ports:
                  - "3306:3306"
                command: mysqld --default-authentication-plugin=mysql_native_password
                environment:
                  MYSQL_ROOT_PASSWORD: abobus
                  MYSQL_USER: forge
                  MYSQL_PASSWORD: bibus
                  MYSQL_DATABASE: forge


        redis:
                image: redis:latest
                ports:
                  - "6379:6379"
